### PR TITLE
New README header style

### PR DESCRIPTION
**Pull request by repi**
Testing with a style tweak for our open source project READMEs to make them a bit cleaner and have a clear single-line description/tagline. 

Converted a few repros to see how it looks like in concrete cases:
- https://github.com/EmbarkStudios/cargo-deny/pull/363
- https://github.com/EmbarkStudios/puffin/pull/41

### CODE REVIEW

**Review by Jake-Shadle — APPROVED** [review]
I like it, much easier to quickly grok and just generally more pleasant....I just wish markdown had a nicer way to center elements so we didn't need the inline HTML, but oh well. :stuck_out_tongue:

**Comment by Jake-Shadle** [comment]
Oh wait, but not totally sure about surround the header in a code block, that one is weird to me.

**Comment by repi** [comment]
>  just wish markdown had a nicer way to center elements so we didn't need the inline HTML, but oh well. 😛

yeah it is a bit silly and sad to have to use ugly html for it, but here we are!

> Oh wait, but not totally sure about surround the header in a code block, that one is weird to me.

I've gone a bit back and forth on that also, it is a little bit odd but does enforce that it is a project/crate name with monospace text and on GitHub gives a certain light grey background for it which looks a little bit nice. stands out a bit more. 

but also does work without it.

**Comment by Jake-Shadle** [comment]
Yah, it does make it more noticeable, but at the same time, it has an emoji, is an `h1`, at the top, and in the center. :wink:

**Comment by celialewis3** [comment]
I dig it! Looks good. Could go either way re: the code block header 🤷, but it's an interesting choice so I say let's just go for it, can change it back later if we hate it.

**Review by celialewis3 — APPROVED** [review]

**Comment by repi** [comment]
sweet, and yeah we can always change it again.

@celialewis3 can you do a tracking issue here in this about updating all of our open source repos (phew) with checkboxes for them?

**Comment by celialewis3** [comment]
@repi yep will do!

**Comment by repi** [comment]
@celialewis3 reminder to file that issue :)

**Comment by celialewis3** [comment]
Right - created it here #36, will add in the rest of the repositories today.

**Pull request merged**
